config/routes.rb
Rails.application.routes.draw do
  root'tasks#index'
  resources :sessions, only: %i[ new create destroy ]
  resources :users, only: %i[ new create show ]
  resources :tasks

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_attribute_enum_value(attr_name, value)
    return if value.blank?
    human_attribute_name("#{attr_name}.#{value}")
  end

  def human_attribute_enum(attr_name)
    self.class.human_attribute_enum_value(attr_name, self.send("#{attr_name}"))
  end

  def self.enum_options_for_select(attr_name)
    self.send(attr_name.to_s.pluralize).map { |k, _| [self.human_attribute_enum_value(attr_name, k), k] }.to_h
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tasks, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: {maximum: 30 }
  validates :content, presence: true
  validates :status, presence: true

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :user

  enum status: { not_started: 0, in_progress: 1, completed: 2 }
  enum priority: { low: 0, medium: 1, high: 2 }

  scope :task_limit, -> { order(end_time: :desc) }
  scope :rank, -> { order(priority: :desc) }
  scope :with_title, -> (title) { where('title LIKE ?', "%#{title}%") }
  scope :with_status, -> (status) { where(status: status) }
  scope :task_and_status, -> (title, status) { with_title(title).with_status(status) }

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                          format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,  presence: true
  before_validation { email.downcase! }
  has_secure_password
  has_many :tasks, dependent: :destroy

  before_update :admin_cannot_update
  before_destroy :admin_cannot_delete

private

def admin_cannot_update
  if User.where(admin: true).count == 1 && will_save_change_to_admin? && !admin
    throw :abort
  end
end

def admin_cannot_delete
  if User.where(admin: true).count == 1 && self.admin
    throw :abort
  end
end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  skip_before_action :logged_in

  def index
    @users = User.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_admin)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    set_admin
  end

  def update
    set_admin
    if @user.update(params_admin)
      flash[:success] = "ユーザー情報を更新しました"
    elsif User.where(admin: true).count == 1 && !@user.admin
      flash[:alert] = "管理者が最後の１人のため、権限を変更できません"
    else
      flash.now[:danger] = '更新に失敗しました'
    end
    redirect_to admin_users_path
  end

  def destroy
    set_admin
    if @user.destroy
      flash[:success] = "削除しました"
    elsif User.where(admin: true).count == 1 && @user.admin
      flash[:alert] = "管理者が最後の１人のため、削除できません"
    else
      flash[:alert] = "削除に失敗しました"
    end
    redirect_to admin_users_path
  end

  private

  def set_admin
    @user = User.find(params[:id])
  end

  def params_admin
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def admin_user
    redirect_to tasks_path, alert: "権限がありません" unless current_user.admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  before_action :logged_in, only: [:new]

  private

  def login_required
    redirect_to new_session_path unless current_user
  end

  def logged_in
    redirect_to tasks_path(current_user) if current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :logged_in, only:[:new]
  before_action :login_owner, only: [:show]

  def index
    @tasks = Task.all.order(created_at: :desc)

    if params[:task_limit]
      @tasks = Task.task_limit
    end
    if params[:user_tasks]
      @tasks = current_user.tasks
    end
    if params[:rank]
      @tasks = Task.rank
    end
    if params[:task].present?
      if params[:task][:search].present? && params[:task][:status].present?
        @tasks = @tasks.task_and_status(params[:task][:search], params[:task][:status])
      end
      if params[:task][:search].present?
        @tasks = @tasks.with_title(params[:task][:search])
      end
      if params[:task][:status].present?
        @tasks = @tasks.with_status(params[:task][:status])
      end
      if params[:task][:tag_id].present?
        @tasks = Tag.find(params[:task][:tag_id]).tasks
      end
    end
    @tasks = @tasks.page(params[:page]).per(5)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to task_path(@task), notice: "保存に成功しました"
    else
      flash.now[:danger] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    set_task
  end

  def update
    set_task
      if @task.update(task_params)
        redirect_to tasks_path, notice: "タスクを更新しました"
      else
        flash.now[:danger] = '更新に失敗しました'
        render :edit
      end
  end

  def show
    set_task
  end

  def destroy
    set_task
    @task.destroy
    flash[:success] = "削除しました"
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(%i[title content end_time status priority user_id tag_name], tag_ids: [])
  end

  def login_owner
    task = Task.find(params[:id])
      if current_user != task.user && !current_user.admin
      redirect_to tasks_path, alert: "他のユーザー情報を観覧する権限がありません"
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :login_owner, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    set_user
    @task = @user.tasks.order(priority: :desc).page(params[:page]).per(5)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(%i[name email password password_confirmation])
  end

  def login_owner
    user = User.find(params[:id])
      if current_user != user && !current_user.admin
      redirect_to tasks_path, alert: "他のユーザー情報を観覧する権限がありません"
      end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def priority_class(priority)
    case priority
    when "low"
      "low-priority"
    when "medium"
      "medium-priority"
    when "high"
      "high-priority"
    else
      ""
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>管理者のユーザー編集ページ</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

 
  <%= form_with(model: [:admin, @user], local: true) do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
      <td><%= f.label :email %></td>
      <td><%= f.email_field :email %></td>
    <tr>
      <td><%= f.label :password %>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr>
      <td><%= f.label :admin %>
      <td><%= f.check_box :admin %></td>
    </tr>
    </table>
      <p class="mt-5"><%= f.submit "Create  account" %></p>
      <p><%= link_to t('view.delete'), [:admin, @user], method: :delete, data: { confirm: "ユーザーを削除してもいいですか？" }, class: "btn btn-danger m-5" %></p>
  <% end %>

app/views/admin/users/index.html.erb
<h1>管理者:ユーザー管理ページ</h1>

<%= link_to 'ユーザーを新規登録する', new_admin_user_path %>
<%= link_to 'タスク一覧へ', tasks_path %>

<table class="mt-5">
  <h2 class ="mt-5">管理者</h2>
  <thead>
    <tr>
      <th><%= "ID" %></th>
      <th><%= t 'view.name'  %></th>
      <th><%= t 'view.email'  %></th>
      <th><%= "登録タスク数" %></th>
      <th><%= "管理者権限" %></th>
      <th colspan="2"><%= t 'view.access'  %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.eager_load(:tasks).each.with_index(1) do |user, index| %>
      <tr>
        <% if user.admin %>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.size %></td>
          <td><%= user.admin %></td>
          <td><%= link_to t('view.show'), user, data: { confirm: "#{index}の詳細を確認しますか？" } %></td>
          <td><%= link_to t('view.edit'), edit_admin_user_path(user), data: { confirm: "#{index}のユーザーを編集しますか？" } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<table class="mt-5">
  <h2 class="mt-5">一般ユーザー</h2>
  <thead>
    <tr>
      <th><%= "ID" %></th>
      <th><%= t 'view.name'  %></th>
      <th><%= t 'view.email'  %></th>
      <th><%= "登録タスク数" %></th>
      <th><%= "管理者権限" %></th>
      <th colspan="2"><%= t 'view.access'  %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.eager_load(:tasks).each.with_index(1) do |user, index| %>
      <tr>
        <% if !user.admin %>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.size %></td>
          <td><%= user.admin %></td>
          <td><%= link_to t('view.show'), user, data: { confirm: "#{index}の詳細を確認しますか？" } %></td>
          <td><%= link_to t('view.edit'), edit_admin_user_path(user), data: { confirm: "#{index}のユーザーを編集しますか？" } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='paginate'><%= paginate(@users) %></div>

app/views/admin/users/new.html.erb
<h1>管理者のユーザー新規登録ページ</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <%= form_with(model:[:admin, @user], local: true) do |f| %>
  <table>
  <tr>
    <td><%= f.label :name %></td>
    <td><%= f.text_field :name %></td>
  </tr>
    <td><%= f.label :email %></td>
    <td><%= f.email_field :email %></td>
  <tr>
    <td><%= f.label :password %>
    <td><%= f.password_field :password %></td>
  </tr>
  <tr>
    <td><%= f.label :password_confirmation %>
    <td><%= f.password_field :password_confirmation %></td>
  </tr>
  <tr>
    <td><%= f.label :admin %>
    <td><%= f.check_box :admin %></td>
  </tr>
</table>
 <p class="mt-5"><%= f.submit "Create my account" %></p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;500&family=Noto+Sans+JP&family=Zen+Maru+Gothic&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-light bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand text-light">タスク管理</a>
      <div class="login_user ml-auto text-light">
        <% if logged_in? %>
          <% if current_user.admin? %>
            <p class="text-center mb-0">管理者：<%= current_user.name %></p>
          <% else %>
            <p class="text-center mb-0">ログインユーザー：<%= current_user.name %></p>
          <% end %>
        <% else %>
          <p class="text-center mb-0">ようこそ</p>
        <% end %>
      </div>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div,value, class:"#{key}") %>
    <% end %>
  <div class="info text-left">
    <% if logged_in? %>
    <div class="info-item flex">
      <%= link_to "Profile", user_path(current_user.id), class: "m-5" %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    </div>
      <% if current_user.admin? %>
        <%= link_to 'ユーザー管理ページへ', admin_users_path, class: "m-4 btn btn-info" %>
      <% end %>
    <% else %>
    <div class="info-item flex">
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    </div>
    <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model:@task ,local:true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    </div>
  <table>
    <tr>
      <td><%= form.label :title %></td>
      <td><%= form.text_field :title %></td>
    </tr>
    <tr>
      <td><%= form.label :content %></td>
      <td><%= form.text_area :content %></td>
    </tr>
    <tr>
      <td><%= form.label :end_time %></td>
      <td><%= form.datetime_field :end_time %></td>
    </tr>
    <tr>
      <td><%= form.label :status %></td>
      <td><%= form.select :status, Task.enum_options_for_select(:status) %></td>
    </tr>
    <tr>
      <td><%= form.label :priority %></td>
      <td><%= form.select :priority, Task.enum_options_for_select(:priority) %></td>
    </tr>
    <tr>
      <td><%= form.label 'タグ' %></td>
      <td><%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) %></td>
    </tr>
  </table>

  <p class="mt-4"><%= form.submit "タスクを保存", data: {confirm: "タスクを保存してもいいですか？"} %></p>
  <p><%= link_to "タスク一覧に戻る", tasks_path %></p>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="shadow-lg p-3 mb-5 bg-white rounded"><%= t('view.edit') %></h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 class="shadow-lg p-3 mb-5 bg-white rounded"><%=t('view.list')%></h1>

<%= link_to t('view.New Task'), new_task_path, class: "btn btn-info" %>
<%= link_to "終了期限でソート", tasks_path(task_limit: "true"), class: "btn btn-warning m-5" %>
<%= link_to "優先順位でソート", tasks_path(rank: "true"), class: "btn btn-danger" %>
<%= link_to "自分のタスクのみ表示", tasks_path(user_tasks: "true"), class: "btn btn-danger" %>

<%= form_with url: tasks_path, scope: :task, method: :get, local: true do |form| %>
  <div class="row justify-content-md-center">
    <%= form.text_field :search , id: 'search_input', placeholder: 'タスク名', class: "form-control form-control-lg col-md-4" %>
    <%= form.select :status, Task.enum_options_for_select(:status), include_blank: true, class: "col-md-3" %>
    <%= form.select("tag_id", Tag.pluck(:tag_name, :id), { include_blank: true }) %>
    <%= form.submit 'Search', name: nil %>
  </div>
<% end %>

<table class="mt-5">
  <thead>
    <tr>
      <th>番号</th>
      <th><%= t 'view.title'  %></th>
      <th><%= t 'view.content'  %></th>
      <th><%= t 'view.end_time' %></th>
      <th><%= "名前" %></th>
      <th><%= t 'view.status' %></th>
      <th><%= t 'view.priority' %></th>
      <th><%= t 'view.access'  %></th>
      <th><%= "タグ" %></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each.with_index(1) do |task, index| %>
      <tr>
        <td class="display-4"><%= index %></td>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= l task.end_time %></td>
        <td><%= task.user.name %></td>
        <td><%= task.human_attribute_enum(:status) %></td>
        <td class="<%= priority_class(task.priority) %> display-4" ><%= task.human_attribute_enum(:priority)%></td>
        <td><%= link_to t('view.show'), task, data: { confirm: "#{index}のタスクを確認しますか？" } %></td>
        <td ><% task.taggings.each do |tagging| %>
              <p class="badge bg-info text-light m-1"><%= tagging.tag.tag_name %></p>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='paginate'><%= paginate(@tasks) %></div>

app/views/tasks/new.html.erb
<h1 class="shadow-lg p-3 mb-5 bg-white rounded"><%= t('view.New Task') %></h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1 class="shadow-lg p-3 mb-5 bg-white rounded"><%=t('view.show')%></h1>

<p><%= t 'view.title' %>：<%= @task.title %></p>
<p><%= t 'view.content' %>：<%= @task.content %></p>
<p><%= t 'view.end_time' %>：<%= l @task.end_time %></p>
<p><%= t 'view.status' %>：<%= @task.human_attribute_enum(:status) %></p>
<p><%= t 'view.priority' %>：<%= @task.human_attribute_enum(:priority) %></p>
<p>タグ</p>
<% @task.taggings.each do |tagging| %>
  <p class="badge bg-info text-light"><%= tagging.tag.tag_name %></p>
<% end %>

<p><%= link_to (t 'view.list') , tasks_path %></p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
      <td><%= f.label :email %></td>
      <td><%= f.email_field :email %></td>
    <tr>
      <td><%= f.label :password %>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
  </table>
  <p><%= f.submit "Create my account" %></p>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<p>名前：<%= @user.name %></p>

<p>メールアドレス：<%= @user.email %></p>

<%= link_to 'タスク一覧へ', tasks_path %>

<table class="mt-5">
  <thead>
    <tr>
      <th>番号</th>
      <th><%= t 'view.title'  %></th>
      <th><%= t 'view.content'  %></th>
      <th><%= t 'view.end_time' %></th>
      <th><%= "名前" %></th>
      <th><%= t 'view.status' %></th>
      <th><%= t 'view.priority' %></th>
      <th>タグ</th>
      <th colspan="3"><%= t 'view.access'  %></th>
    </tr>
  </thead>

  <tbody>
    <% @task.each.with_index(1) do |task, index| %>
      <tr>
        <td class="display-4"><%= index %></td>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= l task.end_time %></td>
        <td><%= task.user.name %></td>
        <td><%= task.human_attribute_enum(:status) %></td>
        <td class="<%= priority_class(task.priority) %> display-4" ><%= task.human_attribute_enum(:priority)%></td>
        <td>
          <% task.taggings.each do |tagging| %>
            <p class="badge bg-info text-light"><%= tagging.tag.tag_name %></p>
          <% end %>
        </td>
        <td><%= link_to t('view.show'), task, data: { confirm: "#{index}のタスクを確認しますか？" } %></td>
        <td><%= link_to t('view.edit'), edit_task_path(task), data: { confirm: "#{index}のタスクを編集しますか？" } %></td>
        <td><%= link_to t('view.delete'), task, method: :delete, data: { confirm: "#{index}のタスクを削除してもいいですか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='paginate'><%= paginate(@task) %></div>